version: '3'

env:
  APP: receipt-processor
  PKG: '{{.PKG | default "..."}}'

tasks:
  deps:
    cmds:
      - go mod tidy

  test:
    cmds:
      - go test -p 1 ./$PKG

  build:
    cmds:
      - go build -o ./bin/$APP ./cmd/$APP

  run:
    cmds:
      - ./bin/$APP

  docker-build:
    cmds:
      - docker build -t $APP-build .

  docker-run:
    cmds:    
      - docker run -p 8080:8080 $APP-build