version: '3'

env:
  APP: receipt-processor
  DOCKER_IMAGE: receipt-processor-build
  PKG: '{{.PKG | default "..."}}'

tasks:
  deps:
    cmds:
      - go mod tidy

  test:
    cmds:
      - go test -p 1 ./$PKG

  build:
    cmds:
      - go build -o ./bin/$APP ./cmd/$APP

  run:
    cmds:
      - ./bin/$APP

  docker-build:
    cmds:
      - docker build -t $DOCKER_IMAGE .

  # This assumes that only one container of docker image will be running on a host.
  # If more than one container needs to run,
  # please use `docker run -p 8080:8080 $DOCKER_IMAGE` directly.
  docker-run:
    deps: [docker-cleanup]
    cmds:    
      - docker run -p 8080:8080 --name $DOCKER_IMAGE-app $DOCKER_IMAGE
  
  docker-cleanup:
    cmds:
     - docker rm $DOCKER_IMAGE-app || true